### ISSUE TITLE
レスポンシブへの対応 / handle responsiveness

### ISSUE THREAD

**Issue by hogaku** [yutannihilation/chartist#20]
私はRからレスポンシブに対応したグラフを描くパッケージを探していたものですが、こちらのパッケージでChartist.jsのグラフを描けるということで目が留まりました。ですが、Chartist.jsの特徴でもあるレスポンシブへの対応がまだ実装されておらずそちらへの対応をよろしくお願いします。

**Comment by yutannihilation** [comment]
ありがとうございます。検討します！

**Comment by yutannihilation** [comment]
In English:

Currently, `chartist` package is lacking support for responsiveness, which is one of the main features of Chartist.js. No milestone is set for this enhancement yet, but we undoubtedly need to implement this feature.

Thanks for your suggestion!

**Comment by hogaku** [comment]
Same here! Thank you!
Best regards！

**Comment by yutannihilation** [comment]
Hi @ruscello,

Sorry to have kept you waiting! I added support for responsiveness. An example is available here: http://rpubs.com/yutannihilation/67375.

If you add `resposiveQuery` parameter, the options are used when the query matches.

``` r
chartist(data, day) +
  # default
  Bar(stackBars = FALSE) +
  # For smaller screens
  Bar(stackBars = TRUE, responsiveQuery = "screen and (max-width: 600px)")
```

For details about querying, sorry, I don't know well... The examples on Chartist.js's document may help: http://gionkunz.github.io/chartist-js/examples.html#line-scatter-diagram-with-responsive-settings

Please feel free to reopen this, if you find some bug or inconvenience :+1:

ちなみに、もし日本語でのやりとりがよければ、Github上ではやりづらいので、Twitter([@yutannihilation](https://twitter.com/yutannihilation))か[ブログ](http://notchained.hatenablog.com/entry/2015/02/23/004656)にコメントいただければ助かります。よろしくお願いします！

**Comment by hogaku** [comment]
大変助かります！！
日本語..。.
お手数かけて申し訳ありません。
