### ISSUE TITLE
Line chart labels plugin ;)

### ISSUE THREAD

**Issue by activey** [yutannihilation/chartist#23]
Hey :)

Dunno if somebody would be interested but I've created a custom chartist plugin for line charts, outcome is like this:

![labels](https://cloud.githubusercontent.com/assets/1751891/16521390/d22cbe52-3f96-11e6-8a91-8e97429de9a8.png)

I can put a pull request if relevant.
Cheers

**Comment by activey** [comment]
oops, sorry, wrong repo ...

**Comment by yutannihilation** [comment]
;)
